### ISSUE TITLE
non-zero-indices fails on >1d arrays

### ISSUE THREAD

**Issue by drone29a** [mikera/vectorz-clj#41] opened 2014-09-24 17:20 UTC
The default implementation (in default.clj) of PNonZeroIndices will invoke the array/matrix as a function when attempting to get the non-zero indices for an inner dimension.

**Comment by drone29a** [comment] 2014-09-24 17:24
As an aside, I've run into a number of issues with sparse matrices in Vectorz and core.matrix. Still sorting them out and will report and fix later.

**Comment by mikera** [comment] 2014-09-24 17:48
OK thanks for the report! Sparse matrix support is still a bit experimental, so any help you can give is much appreciated!

Definitely seems like a bug to me.... root cause is probably in core.matrix rather than vectorz-clj, although vectorz.clj should have a fast override of `PNonZeroIndices`

**Comment by mikera** [comment] 2014-10-04 10:48
Fixed in latest release I think.

**Closed as completed by mikera** 2014-10-04 10:48 UTC
Labels: bug
