### ISSUE TITLE
Issue initialising large matrices with data

### ISSUE THREAD

**Issue by scottdw** [mikera/vectorz-clj#40] opened 2014-09-21 17:22 UTC
Using:

``` clojure
[net.mikera/core.matrix "0.29.1"]
[net.mikera/vectorz-clj "0.25.0"]
[org.clojure/clojure "1.6.0"]
```

Attempting to initialise a "large" matrix does not preserve the provided values (all cells are set to 0.0)

``` clojure
(require '[clojure.core.matrix :as mat]) ;; => nil
(mat/current-implementation) ;; => :persistent-vector
(let [w 200 h 500] (mat/esum (mat/matrix (for [y (range h)] (for [x (range w)] (+ x (* y w))))))) ;; => 4999950000
(let [w 250 h 500] (mat/esum (mat/matrix (for [y (range h)] (for [x (range w)] (+ x (* y w))))))) ;; => 7812437500

(mat/set-current-implementation :vectorz) ;; => :vectorz
(let [w 200 h 500] (mat/esum (mat/matrix (for [y (range h)] (for [x (range w)] (+ x (* y w))))))) ;; => 4.99995E9
(let [w 250 h 500] (mat/esum (mat/matrix (for [y (range h)] (for [x (range w)] (+ x (* y w))))))) ;; => 0.0
```

**Comment by mikera** [comment] 2014-09-22 07:04
Confirmed there is some issue here - just trying to verify the cause, should have a fix release done soon.

It's a bit non-trivial as the sparse arrays do some interesting things in order to stay both memory efficient and mutable (like swapping out underlying storage rows).

**Comment by drone29a** [comment] 2014-09-24 17:19
I am encountering this too and have started on workarounds. I'll circle back around once I get a grasp on all the sparse matrix issues.

**Comment by mikera** [comment] 2014-09-24 18:22
The problem appears to actually be in the `assign!` functionality. What's happening is:
- A large `SparseRowMatrix` gets constructed once the number of elements exceeds a certain threshold
- There's a bug somewhere in the code that performs mutable assignment to a whole `SparseRowMatrix` at once.

I'm not yet entirely sure that creating a sparse matrix by default is a good strategy - we probably want to produce sparse matrices only when they are explicitly requested... this is perhaps a separate issue however.

**Comment by mikera** [comment] 2014-09-24 19:48
I think I now have a fix for this in the latest `develop` branch. It will probably need a core.matrix / Vectorz release though to make everything work smoothly so may be a day or two before I get round to doing a set of releases :-)

**Comment by drone29a** [comment] 2014-09-24 23:10
I was also seeing data loss when setting rows, looks like it's related. I have some changes which may fix that, improves performance of setting a vector when the other vector is also sparse, and improves performance of nonZeroIndices for indexed sparse vectors. I'll send a request in a moment.

**Comment by mikera** [comment] 2014-09-25 02:03
OK sounds good!

**Comment by mikera** [comment] 2014-09-25 02:05
Be sure to pull - I was hacking on Vectorz / vectorz-clj last night. I actually got this specific issue fixed in my local snapshot branch of vectorz-clj but still not quite sure what the root cause was, so if you can eliminate any further issues that would be great.

**Comment by drone29a** [comment] 2014-09-25 03:09
Related to large sparse matrices, is there currently not a way to specify SparseHashedVector be used in a Sparse{Row,Column}Matrix? How should one use them for sparse matrices?

**Comment by mikera** [comment] 2014-09-25 03:16
I couldn't think of very many use cases where `SparseHashedVector` is actually preferable - the overhead is just too high compared with `SparseIndexedVector`. So I ended up using SparseIndexedVector by default pretty much everywhere.

In some cases hashes may have a slight edge but it would be an unusual use case. e.g. very large vectors with about 1% density and lots of random elements switching to/from zero in mutable updates.

They are still available for manual construction if people really need them

**Comment by mikera** [comment] 2014-10-10 08:58
OK I think this is all fixed in the latest master. Will push a release out shortly

**Closed as completed by mikera** 2014-10-10 08:58 UTC
Labels: bug
